//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Web.Services.CalculationEngineServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculationEngineServices.ICalculationEngine")]
    public interface ICalculationEngine {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationEngine/ApplyCalculation", ReplyAction="http://tempuri.org/ICalculationEngine/ApplyCalculationResponse")]
        System.Nullable<double> ApplyCalculation(Calculator.Common.Entities.Operation operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationEngine/ApplyCalculation", ReplyAction="http://tempuri.org/ICalculationEngine/ApplyCalculationResponse")]
        System.Threading.Tasks.Task<System.Nullable<double>> ApplyCalculationAsync(Calculator.Common.Entities.Operation operation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculationEngineChannel : Calculator.Web.Services.CalculationEngineServices.ICalculationEngine, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationEngineClient : System.ServiceModel.ClientBase<Calculator.Web.Services.CalculationEngineServices.ICalculationEngine>, Calculator.Web.Services.CalculationEngineServices.ICalculationEngine {
        
        public CalculationEngineClient() {
        }
        
        public CalculationEngineClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationEngineClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationEngineClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationEngineClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Nullable<double> ApplyCalculation(Calculator.Common.Entities.Operation operation) {
            return base.Channel.ApplyCalculation(operation);
        }
        
        public System.Threading.Tasks.Task<System.Nullable<double>> ApplyCalculationAsync(Calculator.Common.Entities.Operation operation) {
            return base.Channel.ApplyCalculationAsync(operation);
        }
    }
}
