//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Calculator.Web.Services.CalculationHelperServices {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="CalculationHelperServices.ICalculationHelper")]
    public interface ICalculationHelper {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationHelper/AddOperationToQueue", ReplyAction="http://tempuri.org/ICalculationHelper/AddOperationToQueueResponse")]
        void AddOperationToQueue(Calculator.Common.Entities.Operation operation);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ICalculationHelper/AddOperationToQueue", ReplyAction="http://tempuri.org/ICalculationHelper/AddOperationToQueueResponse")]
        System.Threading.Tasks.Task AddOperationToQueueAsync(Calculator.Common.Entities.Operation operation);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICalculationHelperChannel : Calculator.Web.Services.CalculationHelperServices.ICalculationHelper, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CalculationHelperClient : System.ServiceModel.ClientBase<Calculator.Web.Services.CalculationHelperServices.ICalculationHelper>, Calculator.Web.Services.CalculationHelperServices.ICalculationHelper {
        
        public CalculationHelperClient() {
        }
        
        public CalculationHelperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CalculationHelperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationHelperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CalculationHelperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void AddOperationToQueue(Calculator.Common.Entities.Operation operation) {
            base.Channel.AddOperationToQueue(operation);
        }
        
        public System.Threading.Tasks.Task AddOperationToQueueAsync(Calculator.Common.Entities.Operation operation) {
            return base.Channel.AddOperationToQueueAsync(operation);
        }
    }
}
